### ISSUE TITLE
Increase DEFAULT_MAX_PORT

### ISSUE THREAD

**Issue by wclr** [Jam3/get-ports#1]
Why is default max port set  DEFAULT_MAX_PORT= 60000?

There is a problem with module that uses higher ports
https://github.com/typicode/minihost/issues/14#issuecomment-196807565

what about allowing up to 65535?

**Comment by mattdesl** [comment]
I'll accept a PR that raises it. :+1: I was simply using [Mikeal's module](https://github.com/mikeal/getport/blob/master/index.js#L8) as a reference for this.
